### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by aveenr** [aveenr/google_finance#1]
- [ ] Dynamic input dates (currently only changes year)
- [x] put url params into dictionary, clean up
- [x] Test download and directories
- [x] Allow other markets (http://www.google.com/intl/en/googlefinance/disclaimer/)
- [x] Validate text file input
- [x] Move variables/constants to config file
- [ ] Get charts for all periods (min, day, year)
